import * as vscode from 'vscode';
import { SerializableTree, DecisionNode, CommitMeta, KnownAgent } from './types';

const AGENT_EMOJI: Record<KnownAgent, string> = {
    claude: '🤖 Claude', gemini: '✨ Gemini', copilot: '🐙 Copilot',
    codex: '🧠 Codex', cursor: '🖱 Cursor', aider: '🛠 Aider',
    devin: '🦾 Devin', coderabbit: '🐇 CodeRabbit',
};

const CLAUDE_MD_START = '<!-- analyzer-tree:start -->';
const CLAUDE_MD_END   = '<!-- analyzer-tree:end -->';

// ── Public API ────────────────────────────────────────────────────────────────

export function generateMarkdown(structureJson: string): string {
    const tree = JSON.parse(structureJson) as SerializableTree;
    const commits = extractCommits(tree);
    const root = tree.nodes.find(n => n.node.uuid === tree.root_uuid);
    const projectName = root?.node.label ?? 'Project';
    const totalTokens = tree.total_tokens;
    const budget      = tree.token_budget;

    const recent   = commits.slice(-30).reverse();   // newest first, last 30
    const aiCommits = commits.filter(c => c.meta?.agent);
    const branches  = commits.filter(c => c.role === 'alternative');

    const lines: string[] = [];

    // ── Header ──────────────────────────────────────────────────────────────
    lines.push(`# ${projectName} — Context Tree`);
    lines.push(`> ${commits.length} commits · ${fmtTok(totalTokens)} tokens · budget ${fmtTok(budget)}`);
    lines.push('');

    // ── Recent changes ───────────────────────────────────────────────────────
    lines.push('## Recent Changes');
    lines.push('| Hash | Author | Message | +/- |');
    lines.push('|------|--------|---------|-----|');
    for (const c of recent.slice(0, 25)) {
        const m    = c.meta;
        const hash = m?.short_hash ?? c.uuid.slice(0, 7);
        const who  = m?.agent ? (AGENT_EMOJI[m.agent] ?? m.agent) : (m?.author_name ?? '—');
        const msg  = truncate(m?.message ?? c.label, 52);
        const diff = m ? `+${m.insertions}/-${m.deletions}` : '—';
        lines.push(`| \`${hash}\` | ${who} | ${msg} | ${diff} |`);
    }
    lines.push('');

    // ── Earliest commits (stack decisions) ──────────────────────────────────
    const early = commits.slice(0, 5);
    if (early.length) {
        lines.push('## Foundation Commits');
        for (const c of early) {
            const m = c.meta;
            const hash = m?.short_hash ?? c.uuid.slice(0, 7);
            const msg  = m?.message ?? c.label;
            lines.push(`- \`${hash}\` ${msg}`);
        }
        lines.push('');
    }

    // ── Branch points ────────────────────────────────────────────────────────
    if (branches.length) {
        lines.push('## Branch Explorations');
        for (const c of branches.slice(0, 10)) {
            const m   = c.meta;
            const who = m?.agent ? (AGENT_EMOJI[m.agent] ?? m.agent) : (m?.author_name ?? '—');
            const msg = truncate(m?.message ?? c.label, 60);
            lines.push(`- → ${who}: ${msg}`);
        }
        lines.push('');
    }

    // ── AI contributions ─────────────────────────────────────────────────────
    if (aiCommits.length) {
        lines.push('## AI Agent Contributions');
        const byAgent: Record<string, number> = {};
        for (const c of aiCommits) {
            const a = c.meta!.agent!;
            byAgent[a] = (byAgent[a] ?? 0) + 1;
        }
        for (const [agent, count] of Object.entries(byAgent)) {
            const emoji = AGENT_EMOJI[agent as KnownAgent] ?? agent;
            lines.push(`- ${emoji}: ${count} commit${count > 1 ? 's' : ''}`);
        }
        lines.push('');
        lines.push('### Recent AI commits');
        for (const c of aiCommits.slice(-10).reverse()) {
            const m    = c.meta!;
            const hash = m.short_hash;
            const who  = AGENT_EMOJI[m.agent!] ?? m.agent!;
            lines.push(`- \`${hash}\` ${who}: ${truncate(m.message, 55)}`);
        }
        lines.push('');
    }

    // ── Footer ───────────────────────────────────────────────────────────────
    lines.push('---');
    lines.push('*Generated by [Analyzer Tree](https://github.com/Rishab741/analyzer-tree). Full history in `.analyzer-tree/context.json`.*');

    return lines.join('\n');
}

export async function writeContextMd(repoRoot: string, markdown: string): Promise<void> {
    try {
        const dir  = vscode.Uri.joinPath(vscode.Uri.file(repoRoot), '.analyzer-tree');
        const file = vscode.Uri.joinPath(dir, 'CONTEXT.md');
        await vscode.workspace.fs.createDirectory(dir);
        await vscode.workspace.fs.writeFile(file, Buffer.from(markdown, 'utf8'));
    } catch { /* non-fatal */ }
}

export async function patchClaudeMd(repoRoot: string, structureJson: string): Promise<void> {
    try {
        const tree       = JSON.parse(structureJson) as SerializableTree;
        const commits    = extractCommits(tree);
        const root       = tree.nodes.find(n => n.node.uuid === tree.root_uuid);
        const projectName = root?.node.label ?? 'Project';
        const aiCommits  = commits.filter(c => c.meta?.agent);
        const lastAi     = aiCommits.at(-1);
        const recent5    = commits.slice(-5).reverse();

        const block = [
            CLAUDE_MD_START,
            '## Project Context (Analyzer Tree)',
            `> **${projectName}** · ${commits.length} commits`,
            `> Full history: \`.analyzer-tree/CONTEXT.md\` · Detailed: \`.analyzer-tree/context.json\``,
            '',
            '### Recent activity',
            ...recent5.map(c => {
                const m   = c.meta;
                const who = m?.agent ? (AGENT_EMOJI[m.agent] ?? m.agent) : (m?.author_name ?? '—');
                return `- \`${m?.short_hash ?? '?'}\` ${who}: ${truncate(m?.message ?? c.label, 55)}`;
            }),
            '',
            lastAi
                ? `### Last AI commit\n\`${lastAi.meta!.short_hash}\` ${AGENT_EMOJI[lastAi.meta!.agent!] ?? lastAi.meta!.agent}: ${truncate(lastAi.meta!.message, 60)}`
                : '',
            CLAUDE_MD_END,
        ].filter(l => l !== '').join('\n');

        const claudeMdUri = vscode.Uri.joinPath(vscode.Uri.file(repoRoot), 'CLAUDE.md');

        let existing = '';
        try {
            const bytes = await vscode.workspace.fs.readFile(claudeMdUri);
            existing = Buffer.from(bytes).toString('utf8');
        } catch { /* file doesn't exist yet */ }

        let updated: string;
        if (existing.includes(CLAUDE_MD_START)) {
            const before = existing.slice(0, existing.indexOf(CLAUDE_MD_START));
            const after  = existing.slice(existing.indexOf(CLAUDE_MD_END) + CLAUDE_MD_END.length);
            updated = before + block + after;
        } else {
            updated = existing
                ? existing.trimEnd() + '\n\n' + block + '\n'
                : block + '\n';
        }

        await vscode.workspace.fs.writeFile(claudeMdUri, Buffer.from(updated, 'utf8'));
    } catch { /* non-fatal */ }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

interface FlatCommit {
    uuid: string;
    label: string;
    role: string;
    meta: CommitMeta | null;
}

function extractCommits(tree: SerializableTree): FlatCommit[] {
    const map = new Map<string, { node: DecisionNode; children: string[] }>();
    for (const sn of tree.nodes) { map.set(sn.node.uuid, sn); }

    const result: FlatCommit[] = [];
    const visited = new Set<string>();

    function dfs(uuid: string): void {
        if (visited.has(uuid)) { return; }
        visited.add(uuid);
        const sn = map.get(uuid);
        if (!sn) { return; }
        const n = sn.node;

        if (n.node_type === 'commit') {
            let meta: CommitMeta | null = null;
            if (n.metadata) {
                try { meta = JSON.parse(n.metadata) as CommitMeta; } catch { /* ignore */ }
            }
            result.push({ uuid: n.uuid, label: n.label, role: n.role, meta });
        }

        for (const child of sn.children) { if (child) { dfs(child); } }
    }

    dfs(tree.root_uuid);
    return result;
}

function fmtTok(n: number): string {
    return n >= 1000 ? (n / 1000).toFixed(1) + 'k' : String(n);
}

function truncate(s: string, max: number): string {
    return s.length > max ? s.slice(0, max - 1) + '…' : s;
}
